version: "3.9"

services:
  front:
    container_name: trading-saas-front
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    tty: false
    networks:
      - trading-saas-net

networks:
  trading-saas-net:
    external: true
