version: "3.9"

services:
  trading-saas-front:
    container_name: trading-saas-front
    image: trading-saas-front:dev
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
